# Generated by Django 3.0.6 on 2020-05-27 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0005_auto_20200527_1131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='closed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Closes')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations', models.ManyToManyField(to='client_portal.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
