# Generated by Django 3.0.6 on 2020-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='UBC', max_length=150),
            preserve_default=False,
        ),
    ]
