# Generated by Django 3.0.6 on 2020-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0002_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('R', 'Recyclable'), ('P', 'Paper'), ('L', 'Landfill'), ('C', 'Compost')], max_length=1)),
            ],
        ),
    ]
