# Generated by Django 3.0.6 on 2020-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0003_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='organization',
            field=models.ManyToManyField(to='client_portal.Organization'),
        ),
    ]
