# Generated by Django 3.0.6 on 2020-05-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0004_trash_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='organization',
        ),
        migrations.AddField(
            model_name='trash',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_portal.Organization'),
            preserve_default=False,
        ),
    ]
